version: "3"

tasks:
  run:
    deps: [build]
    dir: build
    cmds:
      - ./game_of_life
    silent: true
  build:
    deps: [configure]
    sources:
      - src/**
    cmds:
      - cmake --build build
  configure:
    sources:
      - CMakeLists.txt
    cmds:
      - cmake -S . -G Ninja -B build
